name: Ubuntu-Latest Release - GCC (Linux)

on:
  push:
  pull_request:

permissions:
  contents: read

strategy:
  matrix:
    compiler: [gcc, clang]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} on a branch ${{ github.ref_name }} triggered by ${{ github.event_name }}
        uses: actions/checkout@v4

      - run: "echo ${{ github.repository }} has been cloned in the container !"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: ğŸ”„ Installing Meson package build system...
        run: pip install meson

      - name: ğŸ”„ Installing Ninja-build package...
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build -y

      - name: Building the project... (Release)
        env:
          CC: ${{ matrix.compiler }}
        run: |
          echo "ğŸ—ï¸ Setting up Meson build system..."
          make release
          echo "ğŸ‰ Build completed with Meson!"

